name: math
description: math mobile app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0

  # ui
  flutter_svg: ^2.0.6

  # network/data
  freezed_annotation: ^2.2.0
  dio: ^5.3.3
  graphql: ^5.1.3
  shared_preferences: ^2.1.2
  flutter_secure_storage: ^9.0.0

  # DI
  injectable: ^2.1.2
  get_it: ^7.6.0

  # state
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6

  # util
  logger: ^1.4.0
  just_audio: ^0.9.34
  flutter_dotenv: ^5.1.0
  collection: ^1.17.0
  flutter_udid: ^2.0.1
  url_launcher: ^6.1.11

  # authentication
  google_sign_in: ^6.1.5

  findx_dart_client:
    git:
      url: git@github.com:FindX-0/findx_dart_client.git

  static_i18n:
    git:
      url: https://github.com/kume1a/flutter_static_i18n.git
  global_navigator:
    git:
      url: https://github.com/kume1a/flutter_global_navigator.git
  common_utilities:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_utilities
  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models

dev_dependencies:
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  build_runner: ^2.4.5
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - .env.development
    - .env.production
    - .env.local
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logo/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo/logo.png'
  image_path_android: 'assets/logo/logo_transparent_bg.png'
  min_sdk_android: 21

  remove_alpha_ios: true
  adaptive_icon_background: '#ffffffff'

flutter_native_splash:
  color: '#ffffff'
  image: assets/logo/logo_transparent_bg.png

  android_12:
    color: '#ffffff'
    icon_background_color: '#ffffff'
