name: gql_types
description: generated gql types for applciations
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ^3.1.4

dependencies:
  graphql: ^5.1.3

dev_dependencies:
  flutter_lints: ^2.0.1
  graphql_codegen: ^0.13.7
  build_runner: ^2.4.5
